### ISSUE TITLE
Wiki - Algemeen

### ISSUE THREAD

**Issue by kimgarrard** [ManoukK/frontend-applications#3]
In je wiki is bij 25-10 je zin afgebroken, deze moet denk ik nog af geschreven worden. 
Verder zouden stukjes code extra verduidelijking van je problemen of oplossingen kunnen geven.

**Comment by ManoukK** [comment]
Alle missende stukjes en dagen zijn er weer! Per ongeluk verwijderd toen ik pages wilde maken per week. Goed dat Kim het zag!
